// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEYBf3Hw983LXrsHQAcjXfUFUm-x92oqE',
    appId: '1:421585676600:web:a68f24370421dcfb7179cd',
    messagingSenderId: '421585676600',
    projectId: 'sports-car-f0684',
    authDomain: 'sports-car-f0684.firebaseapp.com',
    storageBucket: 'sports-car-f0684.firebasestorage.app',
    measurementId: 'G-P8NYQ3JPT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEyvKFrWsM-ie3gWnciTYzjBDPNAPtRB4',
    appId: '1:421585676600:android:4f248561a7c4f9d17179cd',
    messagingSenderId: '421585676600',
    projectId: 'sports-car-f0684',
    storageBucket: 'sports-car-f0684.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9r2dqXbXek3Xx5k8bjwLnlnDddCyrM10',
    appId: '1:421585676600:ios:3a6a5d08fc7ce1487179cd',
    messagingSenderId: '421585676600',
    projectId: 'sports-car-f0684',
    storageBucket: 'sports-car-f0684.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9r2dqXbXek3Xx5k8bjwLnlnDddCyrM10',
    appId: '1:421585676600:ios:3a6a5d08fc7ce1487179cd',
    messagingSenderId: '421585676600',
    projectId: 'sports-car-f0684',
    storageBucket: 'sports-car-f0684.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEYBf3Hw983LXrsHQAcjXfUFUm-x92oqE',
    appId: '1:421585676600:web:8028b2dc44ee51627179cd',
    messagingSenderId: '421585676600',
    projectId: 'sports-car-f0684',
    authDomain: 'sports-car-f0684.firebaseapp.com',
    storageBucket: 'sports-car-f0684.firebasestorage.app',
    measurementId: 'G-PRYHD79T3Z',
  );
}
